env:
  browser: true
  es2021: true
  jest: true
extends:
  - 'plugin:react/recommended'
  - airbnb
  - airbnb-typescript
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
  project: [./tsconfig.json, craco.config.js]
ignorePatterns: ["/*.*"]
plugins:
  - react
  - '@typescript-eslint'
rules:
  import/prefer-default-export: 0
  react/jsx-props-no-spreading: 0
